# Generated by Django 5.2 on 2025-05-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_source', models.CharField(choices=[('Fixcare', 'Fixcare'), ('Other', 'Other')], max_length=50)),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('Onsite', 'Onsite'), ('Pickup/Drop', 'Pickup/Drop'), ('Walkin', 'Walkin'), ('Rework', 'Rework')], max_length=20)),
            ],
        ),
    ]
