# Generated by Django 5.2 on 2025-05-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sale_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_feedback',
            field=models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Neutral', 'Neutral')], default='Neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='mode_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('None', 'None')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='technician_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='work_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
