# Generated by Django 5.2 on 2025-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancemonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
                ('month_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('days_in_month', models.IntegerField()),
            ],
        ),
    ]
